receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    
  otlp/satellite:
    endpoint: host.docker.internal:17011
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/satellite]
    metrics:
      receivers: [otlp]
      exporters: [prometheus, otlp/satellite]
    logs:
      receivers: [otlp]
      exporters: [otlp/satellite]
