name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: schutzmate/recipeapi
          tags: |
            # Always tag by commit SHA
            type=sha
            
            # Tag release versions (v1.2.3, v1.2, v1)
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            
            # Tag branch name (only for default branch, e.g., master/main)
            type=ref,event=branch,enable={{is_default_branch}}
            
            # Tag Git tags directly
            type=ref,event=tag
          
            # Assign "latest" on default branch
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./RecipeApi
          file: ./RecipeApi/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
